import type { Metadata } from "next";
import Link from "next/link";
import {
  LegalPage,
  LegalSection,
  LegalList,
  LegalTable,
  Strong,
  ExtLink,
  Mail,
  Code,
} from "@/components/legal/LegalPage";
import { LEGAL_UPDATED_EN, PRIVACY_EMAIL } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Privacy Policy | AgentFlow",
  description:
    "AgentFlow privacy policy: what data we process, how we use Google Calendar data, who we share it with and what your rights are.",
  alternates: {
    canonical: "/en/privacy",
    languages: {
      "es-AR": "/privacy",
      en: "/en/privacy",
    },
  },
  openGraph: {
    url: "https://agentflow.casa/en/privacy",
    title: "Privacy Policy | AgentFlow",
    locale: "en_US",
  },
};

export default function PrivacyPageEn() {
  return (
    <LegalPage
      lang="en"
      title="Privacy Policy"
      updated={LEGAL_UPDATED_EN}
      esHref="/privacy"
      enHref="/en/privacy"
      notice="This is an English translation provided for convenience. For users in Argentina, the Spanish version prevails."
    >
      <LegalSection>
        <p>
          This policy explains what personal data AgentFlow processes, why, who
          we share it with and what rights you have. AgentFlow is owned and
          operated by <Strong>MS Group Ventures LLC</Strong>, a company
          organized in the United States, with its address at 30 N Gould St,
          Sheridan, WY 82801, USA (&quot;AgentFlow&quot;, &quot;we&quot;). We
          comply with Argentine Personal Data Protection Law 25,326 and its
          supplementary regulations.
        </p>
      </LegalSection>

      <LegalSection id="scope" title="1. Who this policy applies to">
        <LegalList
          items={[
            <>
              <Strong>Real estate agents</Strong> who use AgentFlow
              (&quot;Users&quot;).
            </>,
            <>
              <Strong>Third parties</Strong> AgentFlow communicates with on
              behalf of a User: buyers, sellers, owners and other agents
              (&quot;Contacts&quot;).
            </>,
            <>
              <Strong>Visitors</Strong> to agentflow.casa and people who join
              the waitlist.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection id="data" title="2. What data we process">
        <LegalTable
          head={["Category", "Examples", "Source"]}
          rows={[
            [
              "User account data",
              "Name, email, WhatsApp number, RE/MAX office, working hours",
              "The User",
            ],
            [
              "WhatsApp messages",
              "Text, voice notes, documents and images exchanged with AgentFlow",
              "Users and Contacts",
            ],
            [
              "Audio transcriptions",
              "Text generated from voice messages",
              "Generated by AgentFlow",
            ],
            [
              "Real estate transaction data",
              "Properties, photos, opportunities, showings, offers, listing authorizations, reservations, documents",
              "Users and Contacts",
            ],
            [
              "Contact data",
              "Name, phone, email, ID type and number, address, role in the transaction",
              "Users and Contacts",
            ],
            [
              "Google Calendar data",
              <a key="g" href="#google-user-data" className="text-accent hover:underline">
                See section 3
              </a>,
              "Google, with your authorization",
            ],
            ["Waitlist", "Email and, optionally, name", "Visitor"],
            [
              "Technical data",
              "Access and error logs needed to operate the service",
              "Generated automatically",
            ],
          ]}
        />
        <p>We do not use third-party advertising or tracking cookies.</p>
      </LegalSection>

      <LegalSection
        id="google-user-data"
        title="3. Google user data (Google Calendar)"
      >
        <p>If you connect your Google account, AgentFlow requests access to:</p>
        <LegalTable
          head={["Permission", "What we use it for"]}
          rows={[
            [
              <>
                See and edit events on your calendars (
                <Code>calendar.events</Code>)
              </>,
              "Create, update and cancel the showing and activity events you coordinate with AgentFlow, and read your existing events to detect overlaps and suggest free time slots",
            ],
            [
              <>
                See the list of your calendars (
                <Code>calendar.calendarlist.readonly</Code>)
              </>,
              "Let you choose which calendar showings are recorded in",
            ],
          ]}
        />
        <p>
          <Strong>How we use it.</Strong> Google Calendar data is used only to
          provide AgentFlow&apos;s scheduling features: detecting conflicts,
          suggesting times, answering your questions about your schedule and
          keeping your showing events in sync. AgentFlow syncs your calendar
          automatically so your schedule stays up to date.
        </p>
        <p>
          <Strong>Limited Use.</Strong> AgentFlow&apos;s use and transfer to any
          other app of information received from Google APIs will adhere to the{" "}
          <ExtLink href="https://developers.google.com/terms/api-services-user-data-policy">
            Google API Services User Data Policy
          </ExtLink>
          , including the Limited Use requirements. In particular:
        </p>
        <LegalList
          items={[
            "We use Google user data only to provide or improve the scheduling features you see in AgentFlow.",
            "We do not sell Google user data or use it for advertising, ad profiling or resale.",
            <>
              <Strong>
                We do not use Google user data to develop, improve or train
                generalized AI or machine-learning models, whether our own or
                third parties&apos;.
              </Strong>
            </>,
            <>
              We transfer Google user data only to the providers listed in{" "}
              <a href="#providers" className="text-accent hover:underline">
                section 5
              </a>{" "}
              when necessary to carry out your request (for example, the AI
              provider that interprets your message), under contractual
              confidentiality obligations.
            </>,
            "No AgentFlow personnel read your Google user data unless (a) you give us explicit consent for specific data (for example, a support request), (b) it is necessary for security purposes such as investigating abuse, or (c) it is required by law.",
          ]}
        />
        <p>
          <Strong>Storage.</Strong> Your Google access token is stored encrypted
          (AES-256-GCM). Synced events are stored in our database with access
          restricted to your account.
        </p>
        <p>
          <Strong>How to revoke access.</Strong> You can disconnect Google
          Calendar at any time from Settings in the AgentFlow web dashboard, or
          at{" "}
          <ExtLink href="https://myaccount.google.com/permissions">
            myaccount.google.com/permissions
          </ExtLink>
          . When you disconnect, we revoke access and delete the calendar data
          synced from Google.
        </p>
      </LegalSection>

      <LegalSection id="purposes" title="4. Why we use data">
        <LegalList
          items={[
            "To provide the service: interpret your requests, coordinate showings, generate and send documents, enhance property photos, track transactions and send reminders.",
            "To communicate with Contacts on behalf of the User who added them or interacts with them.",
            "To remember your working preferences so we can respond better within your account.",
            "Security, abuse prevention, error diagnosis and legal compliance.",
            "Waitlist notices and product updates (you can unsubscribe at any time).",
          ]}
        />
        <p>We do not sell or rent personal data.</p>
      </LegalSection>

      <LegalSection id="providers" title="5. Artificial intelligence and providers">
        <p>
          AgentFlow uses providers that process data on our behalf, only to
          provide the service and under contractual obligations that restrict
          their use of that data.
        </p>
        <LegalTable
          head={["Provider", "Function", "Location"]}
          rows={[
            ["Anthropic", "AI model that interprets messages and decides actions", "USA"],
            ["Meta (WhatsApp Business Platform)", "Sending and receiving WhatsApp messages", "USA"],
            ["OpenAI", "Voice message transcription and property photo enhancement", "USA"],
            ["Google", "Google Calendar integration and maps services", "USA"],
            ["Supabase", "Database, authentication and file storage", "USA"],
            ["Railway", "Server infrastructure", "USA"],
            ["ConvertAPI", "Document-to-PDF conversion", "USA"],
            ["Langfuse", "Technical monitoring of AI operation", "USA"],
            ["Vercel", "Hosting of this website", "USA"],
          ]}
        />
        <p>
          AI-generated responses may contain errors. Listing authorizations are
          generated as drafts for you to review before they are sent. Always
          review any document before sending or signing it.
        </p>
      </LegalSection>

      <LegalSection id="transfers" title="6. International transfers">
        <p>
          Your data is stored and processed outside Argentina, mainly in the
          United States, which does not have an adequacy decision under
          Argentine law. We put contractual safeguards in place with our
          providers. By using AgentFlow you consent to this transfer.
        </p>
      </LegalSection>

      <LegalSection
        id="contacts"
        title="7. Contact data (buyers, sellers and third parties)"
      >
        <p>
          The User who adds or communicates with a Contact through AgentFlow is
          responsible for having a legitimate basis to do so. AgentFlow
          processes that data only for the ongoing real estate transactions. If
          you are a Contact and want to exercise your rights, write to the
          address in{" "}
          <a href="#rights" className="text-accent hover:underline">
            section 10
          </a>
          .
        </p>
      </LegalSection>

      <LegalSection id="retention" title="8. Retention">
        <LegalTable
          head={["Data", "Period"]}
          rows={[
            [
              "Account and transactions",
              "While the account is active, then 12 months or as required by law",
            ],
            ["WhatsApp messages and transcriptions", "12 months from receipt"],
            ["Google Calendar data", "Until you disconnect your Google account"],
            ["Waitlist", "Until you unsubscribe, then up to 30 days"],
            ["Technical logs", "90 days"],
          ]}
        />
      </LegalSection>

      <LegalSection id="security" title="9. Security">
        <p>
          We apply encryption in transit (HTTPS/TLS), encryption of sensitive
          credentials, per-account access control at the database level,
          masking of personal data in technical logs and restricted staff
          access.
        </p>
      </LegalSection>

      <LegalSection id="rights" title="10. Your rights">
        <p>
          Under Law 25,326 you have the right to access, rectify, update and
          delete your data, and to object to its processing. The right of
          access may be exercised free of charge at intervals of no less than
          six months, unless a legitimate interest is shown. Write to us at{" "}
          <Mail address={PRIVACY_EMAIL} />. We respond within the legal
          deadlines.
        </p>
        <p>
          The Argentine Agency for Access to Public Information (AAIP), as the
          supervisory authority under Law 25,326, handles complaints from anyone
          whose rights are affected by non-compliance with data protection
          rules.
        </p>
      </LegalSection>

      <LegalSection id="minors" title="11. Minors">
        <p>
          AgentFlow is intended for real estate professionals aged 18 or over.
          We do not knowingly collect data from minors.
        </p>
      </LegalSection>

      <LegalSection id="changes" title="12. Changes">
        <p>
          We will post any change on this page with its update date. If the
          change is material, we will notify you by WhatsApp or email.
        </p>
      </LegalSection>

      <LegalSection id="contact" title="13. Contact">
        <p>
          MS Group Ventures LLC — 30 N Gould St, Sheridan, WY 82801, USA —{" "}
          <Mail address={PRIVACY_EMAIL} />.
        </p>
        <p>
          See also our{" "}
          <Link href="/en/terms" className="text-accent hover:underline">
            Terms of Use
          </Link>
          .
        </p>
      </LegalSection>
    </LegalPage>
  );
}
